chore: Update Terraform workflow to include Terraform Validate step

diff --git a/.github/workflows/terraform-output.yml b/.github/workflows/terraform-output.yml
--- a/.github/workflows/terraform-output.yml
+++ b/.github/workflows/terraform-output.yml
@@ -80,6 +80,31 @@ jobs:
             - name: Terraform Init
               run: terraform -chdir=$TARGET_DIR init -backend-config="storage_account_name=$TF_STATE_STORAGE_ACCOUNT_NAME" -backend-config="resource_group_name=$TF_STATE_RESOURCE_GROUP_NAME" -backend-config="container_name=$TF_STATE_CONTAINER_NAME" -backend-config="key=$TF_STATE_KEY"
 
+            # Run terraform validate to check the syntax of the configuration files
+            - name: Terraform Validate
+              run: terraform -chdir=$TARGET_DIR validate
+          
+            # Generates an execution plan for Terraform
+            # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
+            - name: Terraform Plan
+              id: tf-plan
+              run: |
+                export exitcode=0
+                terraform -chdir=$TARGET_DIR plan -detailed-exitcode -no-color -out tfplan -var-file=$TF_VAR_FILE || export exitcode=$?
+
+                echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+                
+                if [ $exitcode -eq 1 ]; then
+                  echo Terraform Plan Failed!
+                  exit 1
+                else 
+                  exit 0
+                fi
+
+            # Terraform Apply
+            - name: Terraform Apply
+              run: terraform -chdir=$TARGET_DIR apply -auto-approve
+
             # Get the data in Terraform configurations as JSON files
             - name: Terraform Output
               run: terraform -chdir=$TARGET_DIR output -json > ${{ github.workspace }}/src/${{ matrix.terraform_configuration }}.json
